### ISSUE TITLE
Transfer assets from a contract

### ISSUE THREAD

**Issue by nimmortal** [neow3j/neow3j#72] opened 2019-07-24 07:16 UTC
Hello,

On current NEO blockchain realisation NEO and GAS is native assets with UTXO. 
This cuts off options to transfer assets directly from the contract (in runtime).
I saw that neow3j already support AssetTransfer in general, but it also necessary to provide an example or add such ability to the library to allow send (withdraw) from the contract as contract owner.

If needed I can provide a neon-js code which can do this.

Thanks.

**Comment by claudemiller** [comment] 2019-07-24 08:30
Hey @nimmortal,

Thanks for proposing this issue. 
Are you referring to the following methods from neon-js?
```
export async function addAttributeIfExecutingAsSmartContract<T extends ManagedApiBasicConfig<tx.BaseTransaction>>(config: T): Promise<T> {}

export async function addSignatureIfExecutingAsSmartContract<T extends ManagedApiBasicConfig<tx.BaseTransaction>>(config: T): Promise<T>{}
```
According to the method naming, those methods do what we are looking for. At the moment you would have to do the same manually. I.e. create and attach a script attribute with the script hash of the contract, and create and attach a witness as created in the neon-js method `getVerificationSignatureForSmartContract()`. 

But it makes sense that we integrate this into neow3j.

If you meant something else please provide the code example that you were talking about.

**Comment by nimmortal** [comment] 2019-07-24 08:46
@claudemiller to be honest, I build such TX manually with all inputs/outputs and witness.
I had communication with NEO team and they not mention such methods at all. 

My example of sending GAS from the contract. 
https://gist.github.com/nimmortal/27666e31be329b44da7b820448b85af1

**Comment by claudemiller** [comment] 2019-07-24 11:30
Ok, looks like we can make this into feature.
Just for the record. You're code does something similar than what I have found in neon-js.
```
        const sb2 = Neon.default.create.scriptBuilder();
        sb2.emitPush([]);// the second params of Main(string method, object[] args) in smart contract
        sb2.emitPush(u.str2hexstring("main")); //the first params of Main(string method, object[] args) in smart contract
        let witnessObj = {
            invocationScript: sb2.str, //for verification trigger in smart contract
            verificationScript: "", //keep null, so NEO node will get smart contract code on chain
        };
        let witness2 = new tx.Witness(witnessObj);
```
While in neon-js we have the following.
```
  const contractState = await rpc.Query.getContractState(smartContractScriptHash).execute(url);
  const { parameters } = contractState.result;
  const witness = new tx.Witness({
    invocationScript: "00".repeat(parameters.length),
    verificationScript: ""
  });
```
So instead of building a script the invocation script is just made up of as many zero-valued bytes as there are parameters that the contract takes. 

I don't know the logic behind this yet.

**Comment by claudemiller** [comment] 2019-07-31 14:13
Hey @nimmortal 
On the branch `feature/transfer_from_contract` I added some experimental code to the `AssetTransfer` class that should allow transferring from a smart contract (see [this commit](https://github.com/neow3j/neow3j/commit/0206aa61e7be41947e839385790caaf963d0eb43)). One can now specify a contract's ScriptHash when building the `AssetTransfer` with the `fromContract()` method. The Transfer is then build with Inputs that belong to the contract instead of the account. The account is only used for signing.

Can you test it with your specific smart contract? E.g. like the following
```
    @Test
    public void test() throws IOException {
        Neow3j neow3j = Neow3j.build(new HttpService("http://seed2.aphelion-neo.com:10332"));
        Account a = Account.fromWIF("KxDgvEKzgSBPPfuVfw67oPQBSjidEiqTHURKSDL1R7yGaGYAeYnr").build();
        try {
            AssetTransfer at = new AssetTransfer.Builder(neow3j)
                    .fromContract(new ScriptHash("0ec5712e0f7c63e4b0fea31029a28cea5e9d551f"))
                    .account(a)
                    .toAddress("AK2nJJpJr6o664CWJKi1QRXjqeic2zRp8y")
                    .asset(GASAsset.HASH_ID)
                    .amount(new BigDecimal("0.1"))
                    .build()
                    .sign()
                    .send();
        } catch (ErrorResponseException e) {
            System.out.println(e.getError().getMessage());
        }
    }
```
The problem is that this again relies on the `getunspents` RPC method, which you mentioned do not have access to. 
So if you can't test it, can you give me the source code of a smart contract that you want to use this feature with?
I don't know what a smart contract is doing internally in case someone is doing an asset transfer from it, so I would appreciate a smart contract example for this.

**Comment by nimmortal** [comment] 2019-08-01 08:10
@claudemiller Thank you for example, I will check it asap

**Comment by claudemiller** [comment] 2019-08-01 15:39
@nimmortal I got it to work after the last commit on the `feature/transfer_from_contract` branch.
I used the following simple contract:
```
from boa.interop.Neo.Runtime import GetTrigger, CheckWitness
from boa.interop.Neo.TriggerType import Application, Verification

def Main(password):
    trigger = GetTrigger()
    if trigger == Verification():
        return handleVerification()
    elif trigger == Application():
        return handleApplication(password)
    return False

def handleVerification():
    owner = b'#\xba\'\x03\xc52c\xe8\xd6\xe5"\xdc2 39\xdc\xd8\xee\xe9'
    is_owner = CheckWitness(owner)
    if is_owner:
        return True
    return False
    
def handleApplication(password):
    if password == 'pw':
        return 'banana'
    return False
```
The owner address is 'AK2nJJpJr6o664CWJKi1QRXjqeic2zRp8y'.

This is the neow3j code that does the transfer:
```
String scriptHash = "..." // The contract's script hash
Neow3j neow3j = Neow3j.build(new HttpService("https://node2.neocompiler.io"));
Account a = Account.fromWIF("KxDgvEKzgSBPPfuVfw67oPQBSjidEiqTHURKSDL1R7yGaGYAeYnr").build();
a.updateAssetBalances(neow3j);
try {
  AssetTransfer at = new AssetTransfer.Builder(neow3j)
      .fromContract(new ScriptHash(scriptHash))
      .account(a)
      .toAddress(a.getAddress())
      .asset(NEOAsset.HASH_ID)
      .amount(new BigDecimal("1"))
      .build()
      .sign()
      .send();
  } catch (ErrorResponseException e) {
      System.out.println(e.getError().getMessage());
  }
}
```

I will have to refactor the code before it can be released so it is not yet ready. But it works.

**Comment by claudemiller** [comment] 2019-08-02 16:30
Implemented in version 2.1.0.

**Closed by claudemiller** 2019-08-02 16:30 UTC
Labels: feature

**Comment by nimmortal** [comment] 2019-08-05 15:49
@claudemiller why it is impossible to set tx input? There is any reason for that?

**Comment by claudemiller** [comment] 2019-08-05 16:10
> @claudemiller why it is impossible to set tx input? There is any reason for that?

@nimmortal. No, there is no technical reason for that. We didn't get around to properly handle manually specified inputs yet. Since you brought that up now we will give this more priority.

**Comment by nimmortal** [comment] 2019-08-05 17:25
@claudemiller I want to describe my use case to make reason clear. 
As we know NEO has utxo model and that has huge minuses - we cannot send assets on contract runtime, we need to make an additional tx for that. Also one more issue related to NEO is that when ContractInvocation transaction is failed and assets are attached to then assets is not returned to the caller as a result we need to make 'refund' manually for that. When we do refund it is very handy to have just one tx as input and log such occasions.
