### ISSUE TITLE
RawTransactionAttribute serialize/deserialize method error

### ISSUE THREAD

**Issue by chenquanyu** [neow3j/neow3j#50] opened 2019-06-26 07:51 UTC
The RawTransactionAttribute should be serialized with the TransactionAttributeUsage type. The current logic is not coordinate with neo master-2.x
![image](https://user-images.githubusercontent.com/4393234/60161294-d79d4480-9829-11e9-9238-a6b5e2c231df.png)

![image](https://user-images.githubusercontent.com/4393234/60161407-1f23d080-982a-11e9-8036-53c25bac0de0.png)

**Comment by gsmachado** [comment] 2019-06-26 13:59
This is a duplicate of #47. The issue was already opened and fixed, even before you opened this issue here.

**Closed by gsmachado** 2019-06-26 13:59 UTC
