### ISSUE TITLE
I found a few problems

### ISSUE THREAD

**Issue by WafeiBaBa** [neow3j/neow3j#56] opened 2019-07-04 09:05 UTC
1. For the asynchronous method, it takes a long time to finish after execution, why?
2. When the rpc server returns error, neow3j sdk "getResult" function will only return a null, I think it should return error.message.
3. When I create a new wallet, I have to manually key pairs. I think it is unreasonable. It should be just create the wallet object.
4. When importing and exporting the wallet json file, you need to fill in a "ScryptParams". How do we know what these parameters are for normal developers?

**Comment by gsmachado** [comment] 2019-07-04 11:34
Hello @WafeiBaBa

Thanks for your report. Please, please, please, next time create a different GitHub issue for each of the problems/issues you found. That's a good practice that it's common to be followed in the open source world.

About your questions:

1. We already created a GitHub issue for this. You can take a look at the development here #54 . As state on the issue, this is not a bug. It's because we are using the `Executors.newCachedThreadPool()` and once a thread is used in this thread pool, it takes 60 seconds to be freed. This helps the performance of applications sending a large number of asynchronous calls -- thus, this specific thread pool implementation re-uses threads.

2. Our design pattern is like others in the blockchain industry. The `neow3j` library provides the `.getResult()` method to get the result if the call was successful. If it's not successful, the method `.getError()` returns more information about it. Therefore, I suggest the following: for each call you perform using `neow3j`, you need to check whether `.getResult()` returns something. If the result is not set, then check the `.getError()` for more information.

3. Yes, we acknowledge that `neow3j` should provide an easier way to do that. I created a GitHub issue for this: #57 . We will try to include that for the next release.

4. Can you please provide us more details on how do you use that? Because the (NEP-6 standard)[https://github.com/neo-project/proposals/blob/master/nep-6.mediawiki] describes that a wallet file (.json) must have the scrypt params. That's why `neow3j` expects that such information is always present on the wallet file.

**Comment by gsmachado** [comment] 2019-07-26 22:36
@WafeiBaBa we recently released [version 2.0.1](https://github.com/neow3j/neow3j/releases/tag/2.0.1) that has many fixes and new features. Maybe you could check it out.

The points (3) and (4) of your issue was addressed in the neow3j 2.x version.
We created an issue for the point (1), and you can follow the progress on #54 in the future.

I will close this issue. If you have other questions, please ask us on the NEO Discord, channel #java.

**Closed by gsmachado** 2019-07-26 22:36 UTC
Labels: good first issue, question
