### ISSUE TITLE
Migrate release process away from Bintray/JCenter

### ISSUE THREAD

**Issue by csmuller** [neow3j/neow3j#429] opened 2021-02-22 08:38 UTC
Bintray/JCenter will shutdown their services at the end of March (see [this](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/) blog entry). We need to migrate our release process to a new service, probably back to the Sonatype Nexus Repository Manager.

**Comment by gsmachado** [comment] 2021-03-03 21:20
@csmuller I researched this a bit today.

So, let me list some options:

1. There are multiple places where we could switch to... like, e.g., JFrog Artifactory, Jitpack, GitHub Registry, and others.

However, the problem is that Gradle doesn't provide clauses (or shortcuts) like `jcenter()` or `mavenCentral()` to easily add a repository to the `build.gradle` file. 

2. The easiest option for our users would be to stay with `mavenCentral()` if we consider that this an important factor for usability -- even if that is a sad option hehe.

The good thing about option (2) is that's default. The bad thing is the fucking pain in the ass to directly publish to Sonatype.

3. Another option would be to publish neow3j in our own maven repository. Something like this:

```
repositories {
    maven {
        url "https://maven.neow3j.io/"
    }
```

Advantages of option (3) are:
- Very easy to publish, and work 100% of the time, reliably
- We could customize to our own needs over time

Disadvantages of option (3) are:
- Cost of bandwidth, since we would need to maintain our own infrastructure
- People would need to add the `maven { url "https://maven.neow3j.io/" }` clause in their `build.gradle`, making the already complex set-up of a neow3j project a bit worse.

4. Combine option (1) with something discussed [in this post](https://stackoverflow.com/questions/45422416/how-to-define-a-helper-method-for-gradle-repository). Since we already have a Gradle plugin, we could make the gradle plugin to create such "helper method", somehow.

This would make developer's life a bit easier, but it would still require them to add something like `repositories { neow3jRepo() }` in their `gradle.build` file -- which is not the default.

**Comment by gsmachado** [comment] 2021-03-03 21:22
If we decide to simply go with option (2) for now, I might instead close this issue and create another one to check if there are better plugins to publish to SonaType/MavenCentral somehow. It's not possible that people go through this pain every time they need to release something. 😮

**Comment by gsmachado** [comment] 2021-03-03 21:36
I must admit that the concept of [Jitpack](https://jitpack.io) is absolutely interesting and **deadly easy** to publish (in the maintainer's point of view).

The problem is as I stated before: it requires the user to add a custom `maven { }` clause.

**Comment by gsmachado** [comment] 2021-03-04 17:15
While discussing with @csmuller, we decided that option (2) is the best for us, at the moment. We will try to make a manual release using Sonatype website next time, for version `3.8.0`.

In addition, anyone can already use JitPack by using the following config:

```
repositories {
    maven {
        url "https://jitpack.io/"
    }
}

dependencies {
     implementation 'com.github.neow3j:neow3j:3.7.1‘
}
```

**Closed by gsmachado** 2021-03-04 17:15 UTC
